# Generated by Django 6.0.3 on 2026-03-21 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
